Addition of icons for common folders and change of the "txt" icon.
miguelsolorio/vscode-symbols pull request #269
Opened 2024-12-20 03:46 UTC by VictorManoel

**Is this a new icon or an update to an existing?**
- [x] New icon
- [x] Update to an existing icon

**Did you test your changes in the extension?**
- [x] Yes
- [ ] No

**Did you follow the [contribution guidelines](https://github.com/miguelsolorio/vscode-symbols?tab=readme-ov-file#contributing)?**
- [x] Yes
- [ ] No

**Screenshots (Before and After)**

![before_exemplo](https://github.com/user-attachments/assets/c3bf7fa8-526e-4f98-8ef3-d706f38f95d9)
![after_exemplo](https://github.com/user-attachments/assets/c16e7cef-2d3c-483b-9472-da2d98d6f86e)

**Describe the changes**

I created new icons for the Documents, Files, Build, and .vscode folders. I also changed the ".txt" file icon to one that I believe is more appropriate.

2024-12-20 20:58 UTC, miguelsolorio requested changes
Thanks for the PR, not sure I'm a fan of the doc folder icons (they look too bulky). If you won't mind finding an alternative or reverting them, that would be appreciated.

2025-01-15 05:03 UTC, steniooliv commented
cool...
maybe just resize the docs icon in 10-20%?

2025-05-04 05:41 UTC, miguelsolorio approved these changes
LGTM, thanks for the PR 🫶 made some minor changes

2025-05-04 05:41 UTC, merged

2025-05-04 06:07 UTC, VictorManoel commented
Sorry for disappearing, I had some problems. But I'm already planning some more icons for the future!